name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username gokhanus --password ${{ secrets.GH_TOKEN }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
        docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
